# Generated by Django 3.0.1 on 2022-11-22 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('link', models.CharField(max_length=250)),
                ('another_link', models.CharField(blank=True, max_length=250, null=True)),
                ('image', models.ImageField(upload_to='images')),
            ],
        ),
    ]
