# Generated by Django 3.0.1 on 2022-11-24 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_auto_20221124_1242'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Resume',
        ),
    ]
